services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "main.py"]
    restart: unless-stopped

