# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 120
indent-width = 4

# Assume Python 3.9
target-version = "py39"

[lint]
select = [
    "F",  # Pyflakes
    "E",  # pycodestyle.Error, 修正されない: E501
    "W",  # pycodestyle.Warning
    # "C90",  # mccabe, 修正されないため適用しない
    "I",  # isort
    # "N",  # pep8-naming, 修正されないため適用しない
    "UP",  # pyupgrade
    "A",  # flake8-builtins
    "COM",  # flake8-commas
    "C4",  # flake8-comprehensions(C4)
    "ISC",  # flake8-implicit-str-concat
    "LOG",  # flake8-logging
    "PIE",  # flake8-pie
    "T20",  # flake8-print
    "Q",  # flake8-quotes
    "RET",  # flake8-return
    "SIM",  # flake8-simplify
]
ignore = [
    "W191",   # - ruff formatと競合するlint ruleを除外
    "E111",   # |
    "E114",   # |
    "E117",   # |
    "D206",   # |
    "D300",   # |
    "Q000",   # |
    "Q001",   # |
    "Q002",   # |
    "Q003",   # |
    "COM812", # |
    "COM819", # |
    "ISC001", # |
    "ISC002", # -
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = ["T20"]

[lint.pydocstyle]
convention = "google"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
